//
// ex: set ro:
// DO NOT EDIT.
// generated by smc (http://smc.sourceforge.net/)
// from file : AppClass.sm
//


//
// The contents of this file are subject to the Mozilla Public
// License Version 1.1 (the "License"); you may not use this file
// except in compliance with the License. You may obtain a copy of
// the License at http://www.mozilla.org/MPL/
// 
// Software distributed under the License is distributed on an "AS
// IS" basis, WITHOUT WARRANTY OF ANY KIND, either express or
// implied. See the License for the specific language governing
// rights and limitations under the License.
// 
// The Original Code is State Machine Compiler (SMC).
// 
// The Initial Developer of the Original Code is Charles W. Rapp.
// Portions created by Charles W. Rapp are
// Copyright (C) 2000 - 2003 Charles W. Rapp.
// All Rights Reserved.
//
// Contributor(s): 
//
// State Map
//	This state map is recognizes the regular expression 0*1*.
//
// RCS ID
// $Id$
//
// CHANGE LOG
// $Log$
// Revision 1.5  2005/05/28 13:31:16  cwrapp
// Updated C++ examples.
//
// Revision 1.1  2005/02/21 14:19:18  charlesr
// Added spaces around header file name to test SMC.
//
// Revision 1.0  2003/12/14 19:11:57  charlesr
// Initial revision
//


#include "AppClass.h"
#include "../../lab1/lab1.1\AppClass_sm.h"

using namespace statemap;

// Static class declarations.
Map1_Start Map1::Start("Map1::Start", 0);
Map1_gtalk Map1::gtalk("Map1::gtalk", 1);
Map1_question Map1::question("Map1::question", 2);
Map1_tORc Map1::tORc("Map1::tORc", 3);
Map1_aORh Map1::aORh("Map1::aORh", 4);
Map1_lORa Map1::lORa("Map1::lORa", 5);
Map1_kORt Map1::kORt("Map1::kORt", 6);
Map1_j Map1::j("Map1::j", 7);
Map1_i Map1::i("Map1::i", 8);
Map1_d Map1::d("Map1::d", 9);
Map1_equals Map1::equals("Map1::equals", 10);
Map1_at Map1::at("Map1::at", 11);
Map1_user Map1::user("Map1::user", 12);
Map1_point Map1::point("Map1::point", 13);
Map1_server Map1::server("Map1::server", 14);
Map1_eos Map1::eos("Map1::eos", 15);
Map1_zone Map1::zone("Map1::zone", 16);
Map1_OK Map1::OK("Map1::OK", 17);
Map1_Error Map1::Error("Map1::Error", 18);

void AppClassState::EOS(AppClassContext& context)
{
    Default(context);
}

void AppClassState::a_z(AppClassContext& context, char& ch)
{
    Default(context);
}

void AppClassState::a_zAND0_9(AppClassContext& context, char& ch)
{
    Default(context);
}

void AppClassState::letter_a(AppClassContext& context)
{
    Default(context);
}

void AppClassState::letter_at(AppClassContext& context)
{
    Default(context);
}

void AppClassState::letter_c(AppClassContext& context)
{
    Default(context);
}

void AppClassState::letter_colon(AppClassContext& context)
{
    Default(context);
}

void AppClassState::letter_d(AppClassContext& context)
{
    Default(context);
}

void AppClassState::letter_equals(AppClassContext& context)
{
    Default(context);
}

void AppClassState::letter_h(AppClassContext& context)
{
    Default(context);
}

void AppClassState::letter_i(AppClassContext& context)
{
    Default(context);
}

void AppClassState::letter_j(AppClassContext& context)
{
    Default(context);
}

void AppClassState::letter_k(AppClassContext& context)
{
    Default(context);
}

void AppClassState::letter_l(AppClassContext& context)
{
    Default(context);
}

void AppClassState::letter_point(AppClassContext& context)
{
    Default(context);
}

void AppClassState::letter_question(AppClassContext& context)
{
    Default(context);
}

void AppClassState::letter_t(AppClassContext& context)
{
    Default(context);
}

void AppClassState::other(AppClassContext& context)
{
    Default(context);
}

void AppClassState::Default(AppClassContext& context)
{
    throw (
        TransitionUndefinedException(
            context.getState().getName(),
            context.getTransition()));

}

void Map1_Start::EOS(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_Start::letter_a(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::gtalk);
    context.getState().Entry(context);

}

void Map1_Start::letter_at(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_Start::letter_c(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::gtalk);
    context.getState().Entry(context);

}

void Map1_Start::letter_colon(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_Start::letter_d(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::gtalk);
    context.getState().Entry(context);

}

void Map1_Start::letter_equals(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_Start::letter_h(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::gtalk);
    context.getState().Entry(context);

}

void Map1_Start::letter_i(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::gtalk);
    context.getState().Entry(context);

}

void Map1_Start::letter_j(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::gtalk);
    context.getState().Entry(context);

}

void Map1_Start::letter_k(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::gtalk);
    context.getState().Entry(context);

}

void Map1_Start::letter_l(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::gtalk);
    context.getState().Entry(context);

}

void Map1_Start::letter_point(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_Start::letter_question(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_Start::letter_t(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::gtalk);
    context.getState().Entry(context);

}

void Map1_Start::other(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::gtalk);
    context.getState().Entry(context);

}

void Map1_gtalk::EOS(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_gtalk::letter_a(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::gtalk);
    context.getState().Entry(context);

}

void Map1_gtalk::letter_at(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_gtalk::letter_c(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::gtalk);
    context.getState().Entry(context);

}

void Map1_gtalk::letter_colon(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::question);
    context.getState().Entry(context);

}

void Map1_gtalk::letter_d(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::gtalk);
    context.getState().Entry(context);

}

void Map1_gtalk::letter_equals(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_gtalk::letter_h(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::gtalk);
    context.getState().Entry(context);

}

void Map1_gtalk::letter_i(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::gtalk);
    context.getState().Entry(context);

}

void Map1_gtalk::letter_j(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::gtalk);
    context.getState().Entry(context);

}

void Map1_gtalk::letter_k(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::gtalk);
    context.getState().Entry(context);

}

void Map1_gtalk::letter_l(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::gtalk);
    context.getState().Entry(context);

}

void Map1_gtalk::letter_point(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_gtalk::letter_question(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_gtalk::letter_t(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::gtalk);
    context.getState().Entry(context);

}

void Map1_gtalk::other(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::gtalk);
    context.getState().Entry(context);

}

void Map1_question::EOS(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_question::letter_a(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_question::letter_c(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::tORc);
    context.getState().Entry(context);

}

void Map1_question::letter_colon(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_question::letter_d(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_question::letter_equals(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_question::letter_h(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_question::letter_i(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_question::letter_j(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_question::letter_k(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_question::letter_l(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_question::letter_question(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_question::letter_t(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::tORc);
    context.getState().Entry(context);

}

void Map1_question::other(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_tORc::EOS(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_tORc::letter_a(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::aORh);
    context.getState().Entry(context);

}

void Map1_tORc::letter_c(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_tORc::letter_colon(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_tORc::letter_d(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_tORc::letter_equals(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_tORc::letter_h(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::aORh);
    context.getState().Entry(context);

}

void Map1_tORc::letter_i(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_tORc::letter_j(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_tORc::letter_k(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_tORc::letter_l(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_tORc::letter_question(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_tORc::letter_t(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_tORc::other(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_aORh::EOS(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_aORh::letter_a(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::lORa);
    context.getState().Entry(context);

}

void Map1_aORh::letter_c(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_aORh::letter_colon(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_aORh::letter_d(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_aORh::letter_equals(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_aORh::letter_h(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_aORh::letter_i(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_aORh::letter_j(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_aORh::letter_k(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_aORh::letter_l(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::lORa);
    context.getState().Entry(context);

}

void Map1_aORh::letter_question(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_aORh::letter_t(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_aORh::other(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_lORa::EOS(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_lORa::letter_a(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_lORa::letter_c(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_lORa::letter_colon(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_lORa::letter_d(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_lORa::letter_equals(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_lORa::letter_h(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_lORa::letter_i(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_lORa::letter_j(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_lORa::letter_k(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::kORt);
    context.getState().Entry(context);

}

void Map1_lORa::letter_l(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_lORa::letter_question(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_lORa::letter_t(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::kORt);
    context.getState().Entry(context);

}

void Map1_lORa::other(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_kORt::EOS(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_kORt::letter_a(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_kORt::letter_c(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_kORt::letter_colon(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_kORt::letter_d(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_kORt::letter_equals(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_kORt::letter_h(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_kORt::letter_i(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_kORt::letter_j(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_kORt::letter_k(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_kORt::letter_l(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_kORt::letter_question(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::j);
    context.getState().Entry(context);

}

void Map1_kORt::letter_t(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_kORt::other(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_j::EOS(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_j::letter_a(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_j::letter_c(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_j::letter_colon(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_j::letter_d(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_j::letter_equals(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_j::letter_h(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_j::letter_i(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_j::letter_j(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::i);
    context.getState().Entry(context);

}

void Map1_j::letter_k(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_j::letter_l(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_j::letter_question(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_j::letter_t(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_j::other(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_i::EOS(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_i::letter_a(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_i::letter_c(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_i::letter_colon(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_i::letter_d(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_i::letter_equals(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_i::letter_h(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_i::letter_i(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::d);
    context.getState().Entry(context);

}

void Map1_i::letter_j(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_i::letter_k(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_i::letter_l(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_i::letter_question(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_i::letter_t(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_i::other(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_d::EOS(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_d::letter_a(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_d::letter_c(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_d::letter_colon(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_d::letter_d(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::equals);
    context.getState().Entry(context);

}

void Map1_d::letter_equals(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_d::letter_h(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_d::letter_i(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_d::letter_j(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_d::letter_k(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_d::letter_l(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_d::letter_question(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_d::letter_t(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_d::other(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_equals::EOS(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_equals::letter_a(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_equals::letter_c(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_equals::letter_colon(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_equals::letter_d(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_equals::letter_equals(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::at);
    context.getState().Entry(context);

}

void Map1_equals::letter_h(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_equals::letter_i(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_equals::letter_j(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_equals::letter_k(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_equals::letter_l(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_equals::letter_question(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_equals::letter_t(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_equals::other(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_at::EOS(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_at::a_z(AppClassContext& context, char& ch)
{

    context.getState().Exit(context);
    context.setState(Map1::user);
    context.getState().Entry(context);

}

void Map1_at::a_zAND0_9(AppClassContext& context, char& ch)
{

    context.getState().Exit(context);
    context.setState(Map1::user);
    context.getState().Entry(context);

}

void Map1_at::letter_at(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_at::letter_point(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_at::other(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_user::EOS(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_user::a_z(AppClassContext& context, char& ch)
{

    context.getState().Exit(context);
    context.setState(Map1::user);
    context.getState().Entry(context);

}

void Map1_user::a_zAND0_9(AppClassContext& context, char& ch)
{

    context.getState().Exit(context);
    context.setState(Map1::user);
    context.getState().Entry(context);

}

void Map1_user::letter_at(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::point);
    context.getState().Entry(context);

}

void Map1_user::letter_point(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_user::other(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_point::EOS(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_point::a_z(AppClassContext& context, char& ch)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.addServerSymbol(ch);
        context.setState(Map1::server);
    }
    catch (...)
    {
        context.setState(Map1::server);
        throw;
    }
    context.getState().Entry(context);

}

void Map1_point::a_zAND0_9(AppClassContext& context, char& ch)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.addServerSymbol(ch);
        context.setState(Map1::server);
    }
    catch (...)
    {
        context.setState(Map1::server);
        throw;
    }
    context.getState().Entry(context);

}

void Map1_point::letter_at(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_point::letter_point(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_point::other(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_server::EOS(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_server::a_z(AppClassContext& context, char& ch)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.addServerSymbol(ch);
        context.setState(Map1::server);
    }
    catch (...)
    {
        context.setState(Map1::server);
        throw;
    }
    context.getState().Entry(context);

}

void Map1_server::a_zAND0_9(AppClassContext& context, char& ch)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.addServerSymbol(ch);
        context.setState(Map1::server);
    }
    catch (...)
    {
        context.setState(Map1::server);
        throw;
    }
    context.getState().Entry(context);

}

void Map1_server::letter_at(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_server::letter_point(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::eos);
    context.getState().Entry(context);

}

void Map1_server::other(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_eos::EOS(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_eos::a_z(AppClassContext& context, char& ch)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.addZoneSymbol(ch);
        context.setState(Map1::zone);
    }
    catch (...)
    {
        context.setState(Map1::zone);
        throw;
    }
    context.getState().Entry(context);

}

void Map1_eos::a_zAND0_9(AppClassContext& context, char& ch)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_eos::letter_at(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_eos::letter_point(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_eos::other(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_zone::EOS(AppClassContext& context)
{
    AppClass& ctxt = context.getOwner();

    context.getState().Exit(context);
    context.clearState();
    try
    {
        ctxt.Acceptable();
        context.setState(Map1::OK);
    }
    catch (...)
    {
        context.setState(Map1::OK);
        throw;
    }
    context.getState().Entry(context);

}

void Map1_zone::a_z(AppClassContext& context, char& ch)
{
    AppClass& ctxt = context.getOwner();

    if (ctxt.getZone().isCorrect())
    {
        context.getState().Exit(context);
        context.clearState();
        try
        {
            ctxt.addZoneSymbol(ch);
            context.setState(Map1::zone);
        }
        catch (...)
        {
            context.setState(Map1::zone);
            throw;
        }
        context.getState().Entry(context);
    }
    else
    {
        context.getState().Exit(context);
        context.setState(Map1::Error);
        context.getState().Entry(context);
    }

}

void Map1_zone::a_zAND0_9(AppClassContext& context, char& ch)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_zone::letter_at(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_zone::letter_point(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_zone::other(AppClassContext& context)
{

    context.getState().Exit(context);
    context.setState(Map1::Error);
    context.getState().Entry(context);

}

void Map1_Error::EOS(AppClassContext& context)
{
    AppClass& ctxt = context.getOwner();

    AppClassState& endState = context.getState();

    context.clearState();
    try
    {
        ctxt.Unacceptable();
        context.setState(endState);
    }
    catch (...)
    {
        context.setState(endState);
        throw;
    }

}

void Map1_Error::a_z(AppClassContext& context, char& ch)
{


}

void Map1_Error::a_zAND0_9(AppClassContext& context, char& ch)
{


}

void Map1_Error::letter_a(AppClassContext& context)
{


}

void Map1_Error::letter_at(AppClassContext& context)
{


}

void Map1_Error::letter_c(AppClassContext& context)
{


}

void Map1_Error::letter_colon(AppClassContext& context)
{


}

void Map1_Error::letter_d(AppClassContext& context)
{


}

void Map1_Error::letter_equals(AppClassContext& context)
{


}

void Map1_Error::letter_h(AppClassContext& context)
{


}

void Map1_Error::letter_i(AppClassContext& context)
{


}

void Map1_Error::letter_j(AppClassContext& context)
{


}

void Map1_Error::letter_k(AppClassContext& context)
{


}

void Map1_Error::letter_l(AppClassContext& context)
{


}

void Map1_Error::letter_point(AppClassContext& context)
{


}

void Map1_Error::letter_question(AppClassContext& context)
{


}

void Map1_Error::letter_t(AppClassContext& context)
{


}

void Map1_Error::other(AppClassContext& context)
{


}

//
// Local variables:
//  buffer-read-only: t
// End:
//
